import Head from "next/head";
import { useEagerConnect } from "src/hooks/useEagerConnect";
import ConnectWallet from "@/components/ConnectWallet/ConnectWallet";
import { ConnectionDetails } from "@/components/ConnectionDetails/ConnectionDetails";
import { SignMessage } from "@/components/SignMessage/SignMessage";
import { SimpleRW } from "@/components/SimpleRW/SimpleRW";

export default function Home() {
  useEagerConnect();

  return (
    <div>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-8">
        <h1 className="text-h2 sm:text-h1 leading-none font-extrabold text-black tracking-tight mb-8">
          Welcome to Neptune Mutual
        </h1>
        <ConnectWallet />
        <ConnectionDetails />
        <SignMessage />
        <SimpleRW />
      </main>
    </div>
  );
}
